### ISSUE TITLE
US12 Mindfulness Page

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/S.M.A.R.T.-App#20]
## Value proposition

As a User 
I want to be able to visit the mindfulness page
So that I can get some tips on how to stay mindful

## Description

![Image](https://user-images.githubusercontent.com/132472335/254898527-312b78f0-4f81-4e44-a00c-83ef085385b4.png)

## Acceptance criteria

- [ ] A header called Be Mindful exists
- [ ] On the page there are different exercises to be mindful
- [ ] each exercise has its own card

## Tasks

- [ ] Create a feature branch `mindfulnesspage`
- [ ] create a mindfulness page component
- [ ] create cards to display the exercises/tips
- [ ] add exercises/tips to the cards

**Comment by DErdmann1** [comment]
I like that Feature! :)
