### ISSUE TITLE
US13 Mental Health Resources Page

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/S.M.A.R.T.-App#21]
##Mental Health Resources Page

## Value proposition

As a User 
I want to be able to visit a page that display various mental health resources
So that I can easily move through the app

## Description

![Image](https://user-images.githubusercontent.com/132472335/254859453-73394f90-d5ee-4753-b7d2-22c7df9346aa.png)

## Acceptance criteria

- [ ] A header titled "be Safe" is present on the page.
- [ ] The page displays a list of mental health organizations with their names and contact information.
- [ ] Each entry should have its own card
- [ ] Each  entry in the list should have a clickable link or button to access more details or their website.

## Tasks

- [ ] Create a Feature Branch called `mentalhealthinfo`
- [ ] Create a Mental Health Resources Page Component
- [ ] Add Header to the Page
- [ ] Display Mental Health Organizations Data
- [ ] Create Organization Detail Card Component

**Comment by HannesOster** [comment]
Hi Cornelius,

In your acceptance criteria i saw the line:

" A header titled "be Safe" is present on the page."

Did you mean "be smart" maybe?

Otherwise i cant see a corresponding heading in your description...
