### ISSUE TITLE
US13 Form Styling/Refactoring

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/S.M.A.R.T.-App#26]
## Value proposition

As a User 
I want to be able to see a styled form
So that I can have a nice experience

## Description

The current version of the Form is one page with 6 questions in their own fieldsets. I want to create a card that contains one question per card and style it.

## Acceptance criteria

- [ ] `FormCard` component exists
- [ ] it is rendered for each question when creating a new goal or editing an existing goal
- [ ] the styling fits the theme of the app

## Tasks

- [ ] Create a feature branch `formstyling`
- [ ] create a `FormCard` component
- [ ] render the component in every part of the app the form is present

**Comment by ekat-br** [comment]
LGTM 👍
