### ISSUE TITLE
US14 Footer

### ISSUE THREAD

**Issue by CorneliusMoe** [CorneliusMoe/S.M.A.R.T.-App#28]
## Value proposition

As a User 
I want to have footer on certain pages
So that I can have a better user experience

## Acceptance criteria

- [ ] Different Footer components exist (Formpage, GoalDetailpage,Editpage)
- [ ] These Footers have different Icons, depending on their location
- [ ] The Footer on the Formpage should have a Save Icon and a Back arrow
- [ ] The Footer on the Goaldetailpage should have an Edit Icon, a Delete Icon and a Back arrow
- [ ] The Footer on the Editpage should have a Cancel and a Save Icon
- [ ] Clicking the Icons should call the linked functions

## Tasks

- [ ] Create a feature branch `footer`
- [ ] create three footer components
- [ ] import necessary SVGs
- [ ] rewrite the existing functions for going back, editing,saving,deleting and cancelling

**Comment by MonaHer** [comment]
LGTM :) 🐩
